### ISSUE TITLE
Error-request failed with status code 404 at create error

### ISSUE THREAD

**Issue by Norwestbacon** [cscape/vitalsource-dl#6]
I'm receiving this error when trying to run the script.  Has anyone had any success with this project in the last few months? I notice the axios branch had a commit 2 weeks ago.

While I'm 90% sure this uses the header value from the _jigsaw_session cookie, I've tried header values from every cookie stored to no avail.

I'm wondering if vitalsource has made some changes to render the tool unusable.

**Comment by ChristianVaughn** [comment]
I am getting a different error, but also unable to properly download. I think they just patched out the method this tool was using. Wonder if the repo author knows anything about this
```
Fetching https://jigsaw.vitalsource.com/books/9780134671932/epub/META-INF/container.xml
(node:17440) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (C:\Users\cvaug\Desktop\vitalsource-dl\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\cvaug\Desktop\vitalsource-dl\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\cvaug\Desktop\vitalsource-dl\node_modules\axios\lib\adapters\http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:17440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ghost** [comment]
I am getting the same error as well, using both cookies (jig_isbns and _jigsaw_session):

```$ node index.js
Fetching https://jigsaw.vitalsource.com/books/9781645650942/epub/META-INF/container.xml
(node:14896) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (C:\Users\Montiey\Downloads\vitalsource-dl-master\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Montiey\Downloads\vitalsource-dl-master\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Montiey\Downloads\vitalsource-dl-master\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:14896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:14896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by IsadorAkios** [comment]
Hello,  
Last post long time ago,  but same for me : 

```
> vitalsource-dl@1.0.0 start
> node index.js


Fetching https://jigsaw.vitalsource.com/books/200-ARCHIT-77-EN-SG-E/META-INF/container.xml
(node:10946) UnhandledPromiseRejectionWarning: AxiosError: Request failed with status code 404
    at settle (/c/Users/LRPK2991/vitalsource-dl-master/node_modules/axios/dist/node/axios.cjs:1983:12)
    at IncomingMessage.handleStreamEnd (/c/Users/LRPK2991/vitalsource-dl-master/node_modules/axios/dist/node/axios.cjs:3085:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Axios.request (/c/Users/LRPK2991/vitalsource-dl-master/node_modules/axios/dist/node/axios.cjs:4224:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:10946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
